### ISSUE TITLE
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'

### ISSUE THREAD

**Issue by pjaswanthreddy** [davidteather/TikTok-Api#557]
**Trying to get the post details using getTikTokByUrl() method**

```
api.getTikTokByUrl(url, custom_verifyFp='xx')
```
Any leads on how to solve this would be helpful 

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - TikTokApi Version [3.9.5] 
 
**Additional context**
Works fine on my other machine with ubuntu 18.04
tried 
 - use_seleunium=True; installed chrome driver
 -  have playwright installed

**Comment by alzeric** [comment]
Give this a try and see if this helps out your situation

`api = TikTokApi.get_instance(use_selenium=True, executablePath="/path/to/chromedriver")`

**Comment by pjaswanthreddy** [comment]
Hi I did try this one, but now it says 
```
ERROR:root:TikTok response: {
    statusCode: -1,
    itemInfo: {}
} 
```

**Comment by pjaswanthreddy** [comment]
there were a few missing libraries in the os for the playwright to work. I had to manually install the libraries and it's working now. 

```
apt-get install liblcms2-dev
apt-get install libwebpdemux2
apt-get install libwoff-dev
apt-get install libharfbuzz-dev 
apt-get install libepoxy-dev
apt-get install libxkbcommon-x11-dev
```
